# Runs all tests from the master branch on Mondays at 3 am (UTC time)
name: Cron Testing

on:
  schedule:
    - cron:  '* 3 * * mon'

jobs:
    tests:
      uses: pylhc/.github/.github/workflows/cron.yml@master
      with:
        pytest-options: -m "not cern_network"
