# Build documentation
# The build is uploaded as artifact if triggered from a pull request
# The build is published to GitHub pages if triggered by a push to the master branch (which requires merging a PR)
name: Build and upload documentation

# Runs on the following conditions:
# - Any push to master branch (which requires merging a PR)
# - Any push to a branch linked to a pull request
on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  documentation:
        uses: pylhc/.github/.github/workflows/documentation.yml@master
